SELECT
	CL.ID as ID,
	CL.C_1 as CODE, 
	CL.C_2 as NAME, 
	CL.C_3 as INN, 
	(
		SELECT 
			PROPS.C_4
		FROM
			IBS.VW_CRIT_PROPERTIES PROPS,
			IBS.VW_CRIT_VND_CL_CORP CL2
		WHERE	
			CL.ID = CL2.ID AND
			PROPS.COLLECTION_ID = CL2.REF51	AND PROPS.REF3 = (SELECT ID FROM IBS.VW_CRIT_PROPERTY_GRP WHERE C_2 = 'BUSINESS_SEGMENT' ) 
	) as SEGMENT,
	(
		SELECT 
			PROPS.C_4
		FROM
			IBS.VW_CRIT_PROPERTIES PROPS,
			IBS.VW_CRIT_VND_CL_CORP CL2
		WHERE	
			CL.ID = CL2.ID AND
			PROPS.COLLECTION_ID = CL2.REF51	AND PROPS.REF3 = (SELECT ID FROM IBS.VW_CRIT_PROPERTY_GRP WHERE C_2 = 'BUSINESS_LINE' ) 
	) as LINE,
	( 
		SELECT 
			LISTAGG(C_1, ', ') WITHIN GROUP(order by C_2) 
		FROM 
			IBS.VW_CRIT_${BANK}_LOAN_INSPECTOR
		WHERE 
			COLLECTION_ID = CL.REF37 
			and C_3 is NULL 
	) as PL,
	( 
		SELECT 
			 LISTAGG(C_1, ', ') WITHIN GROUP(order by C_2) 
		FROM 
			IBS.VW_CRIT_${BANK}_LOAN_INSPECTOR 
		WHERE 
			COLLECTION_ID = CL.REF38 
			and C_3 is NULL 
	) as CURATOR,
	NVL(
			(select to_char(min(C_1), 'DD.MM.YYYY') from IBS.VW_CRIT_CL_INFO_REQ where REF2 = CL.ID), 
			(select to_char(min(C_13), 'DD.MM.YYYY') from IBS.VW_CRIT_AC_FIN where REF3 = CL.ID or REF20 = CL.ID)
	) as DATE_BEGIN --дата начала отношений				
FROM 
	IBS.VW_CRIT_CL_ORG CL
--where ID = 92077853
