#!/bin/sh

### BEGIN INIT INFO
# Provides:          disk-writer
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:
# Required-Stop:
# Short-Description: Disk writing microservice
# Description:       Disk writing microservice
### END INIT INFO


#. /lib/lsb/init-functions # инфраструктура LSB - решил не использовать
# для установки в Debian - выполнить: insserv disk-writer

#systemctl daemon-reload
#PIDFILE=/var/run/disk-writer.pid


case $1 in
	start)
		echo "starting disk-writer..."
		/usr/bin/node /usr/share/disk-writer/app > /var/log/disk-writer.log &
	;;
	stop)
		echo "stopping disk-writer..."
		killall node
	;;
	restart)
		$0 stop
		sleep 6
		$0 start
	;;
esac

exit 0
